PASSWORDS = {
    'OMS':{
        'UCO':{
            'USERNAME':'xuwenjie',
            'PASSWORD':''
        },
        'YY':{
            'USERNAME':'xuwenjie',
            'PASSWORD':''
        },
        '3PL':{
            'USERNAME':'xuwenjie',
            'PASSWORD':''
        },
        'EL':{
            'USERNAME':'xuwenjie',
            'PASSWORD':''
        },
        'ELC':{
            'USERNAME':'xuwenjie',
            'PASSWORD':''
        },
    },
    'BPP':{
        'UCO':{
            'USERNAME':'xuwenjie',
            'PASSWORD':'xwjxws123@'
        },
        'YY':{
            'USERNAME':'xuwenjie',
            'PASSWORD':'xwjxws123@'
        },
        '3PL':{
            'USERNAME':'xuwenjie',
            'PASSWORD':'xwjxws123@'
        },
        'EL':{
            'USERNAME':'xuwenjie',
            'PASSWORD':'xwjxws123@'
        },
        'ELC':{
            'USERNAME':'xuwenjie',
            'PASSWORD':'xwjxws123@'
        },
    },
    'CRM': {
        'UCO':{
            'USERNAME':'xuwenjie@uco.com',
            'PASSWORD':'xwjxws123A@'
        },
        'YY':{
            'USERNAME':'xuwenjie@youyue.biz',
            'PASSWORD':'xwjxws123A'
        },
        '3PL':{
            'USERNAME':'',
            'PASSWORD':''
        },
        'EL':{
            'USERNAME':'',
            'PASSWORD':''
        },
        'ELC':{
            'USERNAME':'',
            'PASSWORD':''
        },
    },
}